all:
	gcc -o sender_socket sender_socket.c
	gcc -o receiver_socket receiver_socket.c
	gcc -o sender_FIFO sender_FIFO.c 
	gcc -o receiver_FIFO receiver_FIFO.c
	gcc -o sender_sharedmemory sender_sharedmemory.c
	gcc -o receiver_sharedmemory receiver_sharedmemory.c
	 
